<?php

namespace Database\Seeders;

use App\Models\AutobanType;
use App\Models\AutobanTypeTranslation;
use Illuminate\Database\Seeder;

class AutobanTypeTableSeeder extends Seeder
{
  public function run()
  {
    $type = AutobanType::create(["type_title" => "180"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "180"]);
    $type = AutobanType::create(["type_title" => "450"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "450"]);
    $type = AutobanType::create(["type_title" => "580"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "580"]);
    $type = AutobanType::create(["type_title" => "118i Sport Line"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "١١٨ اى سبورت لاين "]);
    $type = AutobanType::create(["type_title" => "180 - Avantgarde"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "١٨٠ - اڤانتجارد"]);
    $type = AutobanType::create(["type_title" => "180 - Progressive"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "١٨٠ - بروجريسڤ"]);
    $type = AutobanType::create(["type_title" => "200 Coupe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٢٠٠ كوبيه "]);
    $type = AutobanType::create(["type_title" => "200 Luxury"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٢٠٠ لاكشرى"]);
    $type = AutobanType::create(["type_title" => "200 Night Edition"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "200 نايت ايدشن"]);
    $type = AutobanType::create(["type_title" => "200 Progressive"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بروجريسڤ ٢٠٠"]);
    $type = AutobanType::create(["type_title" => "200 Sport"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٢٠٠ سبورت"]);
    $type = AutobanType::create(["type_title" => "200 SUV"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٢٠٠ اس يو ڤى"]);
    $type = AutobanType::create(["type_title" => "218i"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٢١٨  اى"]);
    $type = AutobanType::create(["type_title" => "218i Gran Tourer LCI"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٢١٨  اى جران تورر ال سى اى "]);
    $type = AutobanType::create(["type_title" => "300 AMG"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٣٠٠  ايه ام جى "]);
    $type = AutobanType::create(["type_title" => "300 AMG Coupe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٣٠٠ ايه ام جى كوبيه"]);
    $type = AutobanType::create(["type_title" => "300 Cabriolet"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٣٠٠  كابورليه"]);
    $type = AutobanType::create(["type_title" => "30i M"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٣٠ اى ام"]);
    $type = AutobanType::create(["type_title" => "320 AMG"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٣٢٠ ايه ام جى "]);
    $type = AutobanType::create(["type_title" => "320i Exclusive"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٣٢٠ اى اكسكلوسڤ"]);
    $type = AutobanType::create(["type_title" => "320i Luxury"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٣٢٠ اى لاكشرى"]);
    $type = AutobanType::create(["type_title" => "40i"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => " ٤٠ اى"]);
    $type = AutobanType::create(["type_title" => "418i Gran Coupe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٤١٨ اى جران كوبيه"]);
    $type = AutobanType::create(["type_title" => "450 AMG"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٤٥٠ ايه ام جى "]);
    $type = AutobanType::create(["type_title" => "520i Business"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٥٢٠ اى بيزنس"]);
    $type = AutobanType::create(["type_title" => "520i Luxury"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٥٢٠ اى لاكشرى"]);
    $type = AutobanType::create(["type_title" => "530i M-Sport"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٥٢٠ اى ام سبورت"]);
    $type = AutobanType::create(["type_title" => "560 AMG"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "٥٦٠ ايه ام جى "]);
    $type = AutobanType::create(["type_title" => "740Li Pure Excellence"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => " ٧٤٠ ال اى بيور اكسلانس"]);
    $type = AutobanType::create(["type_title" => "A4"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => " ايه 4"]);
    $type = AutobanType::create(["type_title" => "A5"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ايه 5"]);
    $type = AutobanType::create(["type_title" => "Accenta"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكسنتا"]);
    $type = AutobanType::create(["type_title" => "Access"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكسس"]);
    $type = AutobanType::create(["type_title" => "Acenta"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكنتا"]);
    $type = AutobanType::create(["type_title" => "Active"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكتڤ"]);
    $type = AutobanType::create(["type_title" => "Advanced"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ادڤانسد"]);
    $type = AutobanType::create(["type_title" => "Allure"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "الير"]);
    $type = AutobanType::create(["type_title" => "Ambition"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "امبيشن"]);
    $type = AutobanType::create(["type_title" => "AMG G 63"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ايه ام جى جى ٦٣"]);
    $type = AutobanType::create(["type_title" => "AMT GL"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ايه ام تى جى ال"]);
    $type = AutobanType::create(["type_title" => "Anniversary G"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "انيڤيرسرى جى"]);
    $type = AutobanType::create(["type_title" => "Autobiography Dynamic P400"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اوتوبيجرافى دينامك بى 400"]);
    $type = AutobanType::create(["type_title" => "Autobiography P525"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اوتوبيجرافى بى ٥٢٥"]);
    $type = AutobanType::create(["type_title" => "Avantgarde"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => " اڤانتجارد"]);
    $type = AutobanType::create(["type_title" => "Avantgarde+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "  اڤانتجارد+"]);
    $type = AutobanType::create(["type_title" => "Baseline"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بيزلاين"]);
    $type = AutobanType::create(["type_title" => "Basic  F33"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => " بيزك اف ٣٣"]);
    $type = AutobanType::create(["type_title" => "Be Chic"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى شيك"]);
    $type = AutobanType::create(["type_title" => "Box"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "صندوق"]);
    $type = AutobanType::create(["type_title" => "Cabrio"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كابريو"]);
    $type = AutobanType::create(["type_title" => "Cargo 3.8M3"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كارجو ٣.٨ ام ٣"]);
    $type = AutobanType::create(["type_title" => "Cayenne S"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كايان اس "]);
    $type = AutobanType::create(["type_title" => "Chassis"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تشاسيس"]);
    $type = AutobanType::create(["type_title" => "Chili"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تشيلى"]);
    $type = AutobanType::create(["type_title" => "Chili Edition"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تشيلى ايديشن "]);
    $type = AutobanType::create(["type_title" => "City Cross"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سيتى كروس"]);
    $type = AutobanType::create(["type_title" => "Classic"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كلاسيك"]);
    $type = AutobanType::create(["type_title" => "Combi"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كومبى"]);
    $type = AutobanType::create(["type_title" => "Comfort"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كومفورت"]);
    $type = AutobanType::create(["type_title" => "Connected"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كونكتد"]);
    $type = AutobanType::create(["type_title" => "Connected 5D"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => " كونكتد ٥ دى"]);
    $type = AutobanType::create(["type_title" => "Coupe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كوبيه"]);
    $type = AutobanType::create(["type_title" => "Cross"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كروس"]);
    $type = AutobanType::create(["type_title" => "Deluxe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ديلوكس"]);
    $type = AutobanType::create(["type_title" => "Designe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ديزاين"]);
    $type = AutobanType::create(["type_title" => "Distinguished"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ديستنجويشد"]);
    $type = AutobanType::create(["type_title" => "Distinguished 2S"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ديستنجويشد ٢ اس"]);
    $type = AutobanType::create(["type_title" => "Distinguished S"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ديستنجويشد اس"]);
    $type = AutobanType::create(["type_title" => "Double Cabin"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "دوبل كابينة"]);
    $type = AutobanType::create(["type_title" => "Dynamic"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ديناميك"]);
    $type = AutobanType::create(["type_title" => "Dynamic SE 380 HP"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ديناميك اس إي ٣٨٠ اتش بى "]);
    $type = AutobanType::create(["type_title" => "E Hybrid Executive"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "إى هايبرد سبورت اكسيكيوتڤ "]);
    $type = AutobanType::create(["type_title" => "E Hybrid Sport Turismo"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "إى هايبرد سبورت تورزمو "]);
    $type = AutobanType::create(["type_title" => "E200"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "إى ٢٠٠ "]);
    $type = AutobanType::create(["type_title" => "E200 Avantgarde"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "إى ٢٠٠ اڤانتجارد "]);
    $type = AutobanType::create(["type_title" => "E200 Exclusive"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "إى ٢٠٠اكسكلوسڤ"]);
    $type = AutobanType::create(["type_title" => "E300 AMG"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "إى ٣٠٠ ايه ام جى"]);
    $type = AutobanType::create(["type_title" => "Easy"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ايزى "]);
    $type = AutobanType::create(["type_title" => "E-Hybrid"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "إى هايبرد "]);
    $type = AutobanType::create(["type_title" => "Elegance"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ايليجانس"]);
    $type = AutobanType::create(["type_title" => "Elite"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "إليت"]);
    $type = AutobanType::create(["type_title" => "EX"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "إى إكس"]);
    $type = AutobanType::create(["type_title" => "Exclusive"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكسكلوسڤ"]);
    $type = AutobanType::create(["type_title" => "Executive"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكسيكتڤ"]);
    $type = AutobanType::create(["type_title" => "Executive+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكسيكتڤ+ "]);
    $type = AutobanType::create(["type_title" => "Experience"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكسبريانس"]);
    $type = AutobanType::create(["type_title" => "F/O"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اف / اوه"]);
    $type = AutobanType::create(["type_title" => "F/O P360"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اف / اوه  بى ٣٦٠"]);
    $type = AutobanType::create(["type_title" => "F/O P400 LWB"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اف / اوه  بى ٤٠٠ال دابليو بى"]);
    $type = AutobanType::create(["type_title" => "F/O P400 SWB"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اف / اوه  بى ٤٠٠اس دابليو بى"]);
    $type = AutobanType::create(["type_title" => "F/O P525 LWB"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اف / اوه  بى ٥٢٥ال دابليو بى"]);
    $type = AutobanType::create(["type_title" => "F/O P525 SWB"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اف / اوه  بى ٥٢٥اس دابليو بى"]);
    $type = AutobanType::create(["type_title" => "F/O Petrol"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اف / اوه بيترول"]);
    $type = AutobanType::create(["type_title" => "Feel"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "فييل"]);
    $type = AutobanType::create(["type_title" => "Flagship"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "فلاجشب"]);
    $type = AutobanType::create(["type_title" => "FR"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اف ار"]);
    $type = AutobanType::create(["type_title" => "Full Option"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جميع الكماليات"]);
    $type = AutobanType::create(["type_title" => "G 500"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جى ٥٠٠ "]);
    $type = AutobanType::create(["type_title" => "GA"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جى ايه"]);
    $type = AutobanType::create(["type_title" => "GL"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جى ال"]);
    $type = AutobanType::create(["type_title" => "GLS"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جى ال اس"]);
    $type = AutobanType::create(["type_title" => "GLX"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جى ال اكس"]);
    $type = AutobanType::create(["type_title" => "GR Sport"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => " جى ار سبورت "]);
    $type = AutobanType::create(["type_title" => "Grand"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جراند"]);
    $type = AutobanType::create(["type_title" => "Grand Chic"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جراند شيك"]);
    $type = AutobanType::create(["type_title" => "Grand Deluxe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جراند ديلوكس"]);
    $type = AutobanType::create(["type_title" => "Grand Royal C"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جراند رويال سى"]);
    $type = AutobanType::create(["type_title" => "Grand+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جراند+"]);
    $type = AutobanType::create(["type_title" => "GS"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جى اس"]);
    $type = AutobanType::create(["type_title" => "GT Line"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جى تى لاين"]);
    $type = AutobanType::create(["type_title" => "GT Pack Red Interior"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "جى تى باك ريد انتريور"]);
    $type = AutobanType::create(["type_title" => "High Deluxe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "هاى ديلوكس"]);
    $type = AutobanType::create(["type_title" => "Highline"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "هايلاين"]);
    $type = AutobanType::create(["type_title" => "Honorable"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اونوربل"]);
    $type = AutobanType::create(["type_title" => "HSE Dynamic P360"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اتش اس إى ديناميك بى ٣٦٠"]);
    $type = AutobanType::create(["type_title" => "HSE Luxury P340"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اتش اس إى لاكشرى بى ٣٤٠"]);
    $type = AutobanType::create(["type_title" => "HSE P300"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اتش اس إى بى ٣٠٠"]);
    $type = AutobanType::create(["type_title" => "HSE R Dynamic SE P250"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اتش اس إى ار ديناميك اس إى بى ٢٥٠"]);
    $type = AutobanType::create(["type_title" => "Icon"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "أيكون"]);
    $type = AutobanType::create(["type_title" => "Infinity"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "انفينيتى"]);
    $type = AutobanType::create(["type_title" => "Inscription"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "انسكريبشن"]);
    $type = AutobanType::create(["type_title" => "Inspire"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "انسباير"]);
    $type = AutobanType::create(["type_title" => "Insport"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "انسبورت"]);
    $type = AutobanType::create(["type_title" => "Instyle"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "انستايل"]);
    $type = AutobanType::create(["type_title" => "L&K Special Edition0"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ال اند كيه سبيشال ايديشن"]);
    $type = AutobanType::create(["type_title" => "LFC Edition"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ال اف سى ايديشن"]);
    $type = AutobanType::create(["type_title" => "Limited"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ليميتد"]);
    $type = AutobanType::create(["type_title" => "Limited+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ليميتد+"]);
    $type = AutobanType::create(["type_title" => "Live"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "لايڤ"]);
    $type = AutobanType::create(["type_title" => "Longitude"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "لونجتيد"]);
    $type = AutobanType::create(["type_title" => "LS"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ال اس "]);
    $type = AutobanType::create(["type_title" => "LT"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ال تى"]);
    $type = AutobanType::create(["type_title" => "LT+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ال تى +"]);
    $type = AutobanType::create(["type_title" => "LTZ"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ال تى زد"]);
    $type = AutobanType::create(["type_title" => "Luxury"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "لاكشرى"]);
    $type = AutobanType::create(["type_title" => "LX"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ال اكس"]);
    $type = AutobanType::create(["type_title" => "LXI"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ال اكس اى"]);
    $type = AutobanType::create(["type_title" => "LX-S"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ال اكس اس"]);
    $type = AutobanType::create(["type_title" => "M11"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ١١"]);
    $type = AutobanType::create(["type_title" => "M235i xDrive"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام  ٢٣٥ اى اكس درايف "]);
    $type = AutobanType::create(["type_title" => "M33"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٣٣"]);
    $type = AutobanType::create(["type_title" => "M38"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٣٨"]);
    $type = AutobanType::create(["type_title" => "M50i"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٥٠ اى "]);
    $type = AutobanType::create(["type_title" => "M50i Performance"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٥٠ اى بيرفورمانس "]);
    $type = AutobanType::create(["type_title" => "M50i Sport"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٥٠ اى سبورت"]);
    $type = AutobanType::create(["type_title" => "M51"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٥١"]);
    $type = AutobanType::create(["type_title" => "M52"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٥٢"]);
    $type = AutobanType::create(["type_title" => "M53"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٥٣"]);
    $type = AutobanType::create(["type_title" => "M55"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٥٥"]);
    $type = AutobanType::create(["type_title" => "M850i xDrive Convertible"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٨٥٠ ا ى اكس درايف كونڤيرتبل"]);
    $type = AutobanType::create(["type_title" => "M850i xDrive Coupe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام ٨٥٠ ا ى اكس درايف كوبيه"]);
    $type = AutobanType::create(["type_title" => "Macan S"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ماكان اس"]);
    $type = AutobanType::create(["type_title" => "Maxi 5 Seats"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ماكسى فايڤ سيتس"]);
    $type = AutobanType::create(["type_title" => "Maxi High Roof"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ماكسى هاى روف"]);
    $type = AutobanType::create(["type_title" => "Maxi Life"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ماكسى لايف"]);
    $type = AutobanType::create(["type_title" => "Mid Grade"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ميد جريد"]);
    $type = AutobanType::create(["type_title" => "Midline"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ميد لاين"]);
    $type = AutobanType::create(["type_title" => "Midnight"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ميد نايت"]);
    $type = AutobanType::create(["type_title" => "Modern"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "مودرن"]);
    $type = AutobanType::create(["type_title" => "Momentum"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "مومنتوم"]);
    $type = AutobanType::create(["type_title" => "M-Performance"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام بيرفورمانس"]);
    $type = AutobanType::create(["type_title" => "M-Sport"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام سبورت"]);
    $type = AutobanType::create(["type_title" => "M-Sport Roadster"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ام سبورت رودستر"]);
    $type = AutobanType::create(["type_title" => "Opera"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اوبيرا"]);
    $type = AutobanType::create(["type_title" => "Opera A225"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اوبيرا ايه ٢٢٥"]);
    $type = AutobanType::create(["type_title" => "P 700"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٧٠٠"]);
    $type = AutobanType::create(["type_title" => "P 800"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٨٠٠ "]);
    $type = AutobanType::create(["type_title" => "P250 Prestige"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٢٥٠ برستيج"]);
    $type = AutobanType::create(["type_title" => "P250 R Dynamic HSE"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٢٥٠ ار ديناميك اتش اس إى"]);
    $type = AutobanType::create(["type_title" => "P250 R Sport"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٢٥٠ار سبورت "]);
    $type = AutobanType::create(["type_title" => "P250 S"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٢٥٠ اس"]);
    $type = AutobanType::create(["type_title" => "P300 R Convertible"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٣٠٠ ار كونڤرتبل"]);
    $type = AutobanType::create(["type_title" => "P300 R Coupe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٣٠٠ ار كوبيه"]);
    $type = AutobanType::create(["type_title" => "P340 R Convertible"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٣٤٠ ار كونڤرتبل"]);
    $type = AutobanType::create(["type_title" => "P340 R Coupe"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بى ٣٤٠ ار كوبيه"]);
    $type = AutobanType::create(["type_title" => "Panorama"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بانوراما"]);
    $type = AutobanType::create(["type_title" => "Performance"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بيرفورمانس"]);
    $type = AutobanType::create(["type_title" => "Performance line"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بيرفورمانس لاين"]);
    $type = AutobanType::create(["type_title" => "Performance+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بيرفورمانس+"]);
    $type = AutobanType::create(["type_title" => "Petro"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بيترو"]);
    $type = AutobanType::create(["type_title" => "Premier"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بريمير"]);
    $type = AutobanType::create(["type_title" => "Premier+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بريمير+"]);
    $type = AutobanType::create(["type_title" => "Premium"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بريميوم"]);
    $type = AutobanType::create(["type_title" => "Premium S"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بريميوم اس"]);
    $type = AutobanType::create(["type_title" => "Premium SV"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بريميوم  اس ڤى"]);
    $type = AutobanType::create(["type_title" => "Premium+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "بريميوم +"]);
    $type = AutobanType::create(["type_title" => "Prestige"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "برستيج"]);
    $type = AutobanType::create(["type_title" => "Quadrifoglio"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كوادريفوليو"]);
    $type = AutobanType::create(["type_title" => "QWE"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "كيو دابليو إى"]);
    $type = AutobanType::create(["type_title" => "R Design"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ار ديزاين"]);
    $type = AutobanType::create(["type_title" => "R Dynamic HSE 250 HP"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ار ديناميك اتش اس إى ٢٥٠ اتش بى "]);
    $type = AutobanType::create(["type_title" => "R Dynamic HSE 300 HP"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ار ديناميك اتش اس إى ٣٠٠ اتش بى"]);
    $type = AutobanType::create(["type_title" => "R Dynamic HSE 380 HP"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ار ديناميك اتش اس إى ٣٨٠ اتش بى"]);
    $type = AutobanType::create(["type_title" => "R Dynamic SE"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ار ديناميك اس إى  "]);
    $type = AutobanType::create(["type_title" => "R Dynamic SE 250 HP"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => " ار ديناميك اس إى ٢٥٠ اتش بى"]);
    $type = AutobanType::create(["type_title" => "R Dynamic SE P250"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => " ار ديناميك اس إى  بى ٢٥٠"]);
    $type = AutobanType::create(["type_title" => "Red Interior"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ريد انتريور"]);
    $type = AutobanType::create(["type_title" => "Reference"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ريفرينس"]);
    $type = AutobanType::create(["type_title" => "Rivoli"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ريڤولى"]);
    $type = AutobanType::create(["type_title" => "R-Line"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ار لاين"]);
    $type = AutobanType::create(["type_title" => "Royal"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "رويال"]);
    $type = AutobanType::create(["type_title" => "S"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس"]);
    $type = AutobanType::create(["type_title" => "S 580 4MATIC"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس ٥٨٠  فور ماتيك"]);
    $type = AutobanType::create(["type_title" => "S H/B 3 Doors Chili"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس هاتش باك 3 باب تشيلى"]);
    $type = AutobanType::create(["type_title" => "S Line Sportback"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس لاين سبورت باك "]);
    $type = AutobanType::create(["type_title" => "S500 4M"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس ٥٠٠  فور ام"]);
    $type = AutobanType::create(["type_title" => "Salt"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سولت"]);
    $type = AutobanType::create(["type_title" => "Salt Edition"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سولت ايديشن"]);
    $type = AutobanType::create(["type_title" => "SE Hybrid"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس إى هايبرد "]);
    $type = AutobanType::create(["type_title" => "SE Hybrid Executive"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس إى هايبرد سبورت اكسيكيوتڤ"]);
    $type = AutobanType::create(["type_title" => "SE-Hybrid Sport Turismo"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس إى هايبرد سبورت تورزمو"]);
    $type = AutobanType::create(["type_title" => "Shine"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "شاين"]);
    $type = AutobanType::create(["type_title" => "Signature"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سيجنتشر"]);
    $type = AutobanType::create(["type_title" => "Signature+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سيجنتشر+"]);
    $type = AutobanType::create(["type_title" => "S-Line"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس لاين"]);
    $type = AutobanType::create(["type_title" => "Smart"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سمارت"]);
    $type = AutobanType::create(["type_title" => "Smart Fun"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سمارت فن"]);
    $type = AutobanType::create(["type_title" => "Smart RA9"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سمارت ار ايه 9"]);
    $type = AutobanType::create(["type_title" => "Smart Safety"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سمارت سيفتى "]);
    $type = AutobanType::create(["type_title" => "Smart SR"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سمارت اس ار "]);
    $type = AutobanType::create(["type_title" => "Smart V2"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سمارت ڤى 2 "]);
    $type = AutobanType::create(["type_title" => "Smart ZA8"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سمارت زد ايه 8"]);
    $type = AutobanType::create(["type_title" => "Smart+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سمارت +"]);
    $type = AutobanType::create(["type_title" => "Spirit"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبيريت"]);
    $type = AutobanType::create(["type_title" => "Sport"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبورت"]);
    $type = AutobanType::create(["type_title" => "Sport  Intense"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبورت انتنس"]);
    $type = AutobanType::create(["type_title" => "Sport Line"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبورت لاين"]);
    $type = AutobanType::create(["type_title" => "Sport Package"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبورت باكدج "]);
    $type = AutobanType::create(["type_title" => "Sport Performance"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبورت بيرفورمانس"]);
    $type = AutobanType::create(["type_title" => "Sport Turbo"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبورت تربو "]);
    $type = AutobanType::create(["type_title" => "Sport Turismo"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبورت تورزمو"]);
    $type = AutobanType::create(["type_title" => "Sport+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبورت +"]);
    $type = AutobanType::create(["type_title" => "Sportback"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سبورت باك"]);
    $type = AutobanType::create(["type_title" => "Standard"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ستاندرد"]);
    $type = AutobanType::create(["type_title" => "Style"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ستايل"]);
    $type = AutobanType::create(["type_title" => "Style+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ستايل +"]);
    $type = AutobanType::create(["type_title" => "Super"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سوبر"]);
    $type = AutobanType::create(["type_title" => "Super Saloon"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "سوبر صالون "]);
    $type = AutobanType::create(["type_title" => "SV"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس ڤى "]);
    $type = AutobanType::create(["type_title" => "SVR P575"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اس ڤى ار بى ٥٧٥"]);
    $type = AutobanType::create(["type_title" => "T8 Hybrid Excellence 4 Seats"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تى ايت هايبرد اكسلانس 4 سيتس"]);
    $type = AutobanType::create(["type_title" => "Tekna"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تكنا"]);
    $type = AutobanType::create(["type_title" => "TFSI"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تى اف اس اى "]);
    $type = AutobanType::create(["type_title" => "TFSI Quattro"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تى اف اس اى كواترو"]);
    $type = AutobanType::create(["type_title" => "Titanium"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تيتانيوم"]);
    $type = AutobanType::create(["type_title" => "Titanium X"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تيتانيوم اكس "]);
    $type = AutobanType::create(["type_title" => "Topline"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "توبلاين"]);
    $type = AutobanType::create(["type_title" => "Topline GS"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "توبلاين جى اس "]);
    $type = AutobanType::create(["type_title" => "Topline Infinity"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "توبلاين انفنتى "]);
    $type = AutobanType::create(["type_title" => "Topline ZS9"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "توبلاين زد اس 9 "]);
    $type = AutobanType::create(["type_title" => "Topline+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "توبلاين +"]);
    $type = AutobanType::create(["type_title" => "Transportation"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ترانسبورتيشن"]);
    $type = AutobanType::create(["type_title" => "Trend"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ترند "]);
    $type = AutobanType::create(["type_title" => "Trend+"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ترند +"]);
    $type = AutobanType::create(["type_title" => "TSI"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تى اس اى "]);
    $type = AutobanType::create(["type_title" => "Two Tone"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "تو تون "]);
    $type = AutobanType::create(["type_title" => "Ultimate"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "التميت"]);
    $type = AutobanType::create(["type_title" => "Urban"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اوربان"]);
    $type = AutobanType::create(["type_title" => "Van Close 11.5M"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ڤان كلوز ١١.٥ام"]);
    $type = AutobanType::create(["type_title" => "Van Close 15M"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ڤان كلوز ١٥ام"]);
    $type = AutobanType::create(["type_title" => "Van Close 8M"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ڤان كلوز 8 ام "]);
    $type = AutobanType::create(["type_title" => "VAN CNG"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ڤان سى ان جى "]);
    $type = AutobanType::create(["type_title" => "Veloce"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ڤيلوسى"]);
    $type = AutobanType::create(["type_title" => "Visia"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ڤيسيا"]);
    $type = AutobanType::create(["type_title" => "Vision"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ڤيجن"]);
    $type = AutobanType::create(["type_title" => "VRS"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ڤي ار اس "]);
    $type = AutobanType::create(["type_title" => "VTI Highline"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "ڤي تى اى هايلاين"]);
    $type = AutobanType::create(["type_title" => "Xcellence"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكسلانس"]);
    $type = AutobanType::create(["type_title" => "xDrive x30i xLine"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكس درايڤ اكس ٣٠اى اكس لاين"]);
    $type = AutobanType::create(["type_title" => "X-Line"]);AutobanTypeTranslation::create(["autoban_type_id" => $type->id, "locale" => "ar", "type_title" => "اكس لاين "]);
  }
}
