<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use phpDocumentor\Reflection\Types\This;

class Autoban extends Model
{
  use HasFactory;
  protected $fillable = [
    'autoban_model_id',
    'autoban_type_id',
    'autoban_year_id',
    'autoban_price_id',
    'price_list_appearance',
    'market_availability',
    'order',
    "reviewed"
  ];

  protected static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub
    static::addGlobalScope("order",function (Builder $builder){
      $builder->orderBy('order');
    });
  }

  public function model()
  {
    return $this->belongsTo(AutobanModel::class,'autoban_model_id')
      ->with('brand');
  }
  public function type()
  {
    return $this->belongsTo(AutobanType::class,'autoban_type_id')->with('translations');
  }
  public function year()
  {
    return $this->belongsTo(AutobanYear::class,'autoban_year_id')->with('translations');
  }
  public function price()
  {
    return $this->belongsTo(AutobanPrice::class,'autoban_price_id')->with('translations');
  }
  public function pivots()
  {
    return $this->hasMany(AutobanCategory::class);
  }

  public function pivotsOptions()
  {
    return $this->pivots()->with("options");
  }
  public function pivotsOptionsRequired()
  {
    return $this->pivots()->whereHas('category',function ($x){
      return $x->where('required',1);
    })->with('category');
  }

  public function autobanCateory()
  {
    return $this->belongsToMany(
      OptionCategory::class,
      'autoban_category'
    )->withTimestamps();
  }
  /*public function latestOptionUpdate()
  {
    return $this->belongsToMany(
      OptionCategory::class,
      'autoban_category'
    )->latest('updated_at');
  }*/

  public function range()
  {
    return $this->belongsTo(AutobanPrice::class,'autoban_price_id')->with('translations');
  }

  static function latestOrder($autoban_model_id)
  {
    return (Parent::where('autoban_model_id',$autoban_model_id)
      ->latest('order')
      ->first() ?: (Object) ['order'=>-1])->order;
  }
}
